### ISSUE TITLE
dynamic-stack-buffer-overflow in js_bigfloat_parseFloat

### ISSUE THREAD

**Issue by renatahodovan** [bellard/quickjs#266]
Version: 3b45d15
Command: `./qjs --bignum test.js`
Test:
```js
BigFloat.parseFloat();
```

Backtrace:
```
=================================================================
==4161530==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffe78c6c970 at pc 0x55eca9cf4590 bp 0x7ffe78c6c770 sp 0x7ffe78c6c768
READ of size 8 at 0x7ffe78c6c970 thread T0
    #0 0x55eca9cf458f in js_bigfloat_parseFloat quickjs/quickjs.c:51576:9
    #1 0x55eca9b322d8 in js_call_c_function quickjs/quickjs.c:16013:19
    #2 0x55eca9b9ad64 in JS_CallInternal quickjs/quickjs.c:16208:16
    #3 0x55eca9b8ad43 in JS_CallInternal quickjs/quickjs.c:16615:27
    #4 0x55eca9ba8d00 in JS_CallFree quickjs/quickjs.c:18694:19
    #5 0x55eca9ba8d00 in JS_EvalFunctionInternal quickjs/quickjs.c:34348:19
    #6 0x55eca9bc8dab in __JS_EvalInternal quickjs/quickjs.c:34483:19
    #7 0x55eca9baa149 in JS_EvalInternal quickjs/quickjs.c:34501:12
    #8 0x55eca9baa149 in JS_EvalThis quickjs/quickjs.c:34532:11
    #9 0x55eca9baa149 in JS_Eval quickjs/quickjs.c:34540:12
    #10 0x55eca9b2f57e in eval_buf quickjs/qjs.c:71:15
    #11 0x55eca9b2f7bb in eval_file quickjs/qjs.c:103:11
    #12 0x55eca9b2ef9d in main quickjs/qjs.c:516:17
    #13 0x7f4bd7a44d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #14 0x7f4bd7a44e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #15 0x55eca9a706a4 in _start (quickjs/qjs+0x5d6a4) (BuildId: 15d82394339b9ddb47ab9f73cc3261c989737d36)

Address 0x7ffe78c6c970 is located in stack of thread T0 at offset 496 in frame
    #0 0x55eca9cf3cef in js_bigfloat_parseFloat quickjs/quickjs.c:51566

  This frame has 5 object(s):
    [32, 40) 'retval.sroa.0.i' (line 12496)
    [64, 128) 'buf.i.i' (line 6700)
    [160, 168) 'obj.sroa.0.i.i' (line 9840)
    [192, 200) 'v.sroa.0.i.i'
    [224, 228) 'radix' (line 51570) <== Memory access at offset 496 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow quickjs/quickjs.c:51576:9 in js_bigfloat_parseFloat
Shadow bytes around the buggy address:
  0x10004f1858d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004f1858e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004f1858f0: f1 f1 f1 f1 f8 f2 f2 f2 f8 f8 f8 f8 f8 f8 f8 f8
  0x10004f185900: f2 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 04 f3 f3 f3
  0x10004f185910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10004f185920: 00 00 00 00 00 00 00 00 ca ca ca ca 00 00[cb]cb
  0x10004f185930: cb cb cb cb f1 f1 f1 f1 f8 f2 f2 f2 f8 f2 f2 f2
  0x10004f185940: f8 f2 f2 f2 00 00 00 00 00 00 00 00 00 00 f2 f2
  0x10004f185950: f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2 f8 f3
  0x10004f185960: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004f185970: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==4161530==ABORTING
```
The issue was found by libFuzzer with a [Grammarinator](https://github.com/renatahodovan/grammarinator)-based custom mutator.

**Comment by bellard** [comment]
no longer relevant because libbf was removed.
