### ISSUE TITLE
Memory leak in bf_resize

### ISSUE THREAD

**Issue by renatahodovan** [bellard/quickjs#268]
Version: 3b45d15
Command: `./qjs --bignum test.js`
Build: `CONFIG_ASAN=y make`
Test:
```js
1_6_1n ** 69224.3e-6l
```

Backtrace:
```
=================================================================
==4185893==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x55d7e05274ee in __interceptor_malloc (/home/reni/work/sut/quickjs/qjs+0xe04ee) (BuildId: 15d82394339b9ddb47ab9f73cc3261c989737d36)
    #1 0x55d7e0618d83 in js_def_malloc /home/reni/work/sut/quickjs/quickjs.c:1721:11
    #2 0x55d7e0618d83 in js_def_realloc /home/reni/work/sut/quickjs/quickjs.c:1747:16
    #3 0x55d7e07df031 in bf_realloc /home/reni/work/sut/quickjs/./libbf.h:202:12
    #4 0x55d7e07df031 in bf_resize /home/reni/work/sut/quickjs/libbf.c:216:15
    #5 0x55d7e07df031 in bf_set /home/reni/work/sut/quickjs/libbf.c:306:9
    #6 0x55d7e07df031 in check_exact_power2n /home/reni/work/sut/quickjs/libbf.c:4665:5
    #7 0x55d7e07dcd34 in bf_pow /home/reni/work/sut/quickjs/libbf.c:4821:35
    #8 0x55d7e0604735 in js_binary_arith_bigfloat /home/reni/work/sut/quickjs/quickjs.c:13361:15
    #9 0x55d7e0636f3c in js_binary_arith_slow /home/reni/work/sut/quickjs/quickjs.c
    #10 0x55d7e05ccc6f in JS_CallInternal /home/reni/work/sut/quickjs/quickjs.c:18052:17
    #11 0x55d7e05dcd00 in JS_CallFree /home/reni/work/sut/quickjs/quickjs.c:18694:19
    #12 0x55d7e05dcd00 in JS_EvalFunctionInternal /home/reni/work/sut/quickjs/quickjs.c:34348:19
    #13 0x55d7e05fcdab in __JS_EvalInternal /home/reni/work/sut/quickjs/quickjs.c:34483:19
    #14 0x55d7e05de149 in JS_EvalInternal /home/reni/work/sut/quickjs/quickjs.c:34501:12
    #15 0x55d7e05de149 in JS_EvalThis /home/reni/work/sut/quickjs/quickjs.c:34532:11
    #16 0x55d7e05de149 in JS_Eval /home/reni/work/sut/quickjs/quickjs.c:34540:12
    #17 0x55d7e056357e in eval_buf /home/reni/work/sut/quickjs/qjs.c:71:15
    #18 0x55d7e05637bb in eval_file /home/reni/work/sut/quickjs/qjs.c:103:11
    #19 0x55d7e0562f9d in main /home/reni/work/sut/quickjs/qjs.c:516:17
    #20 0x7fb91805dd8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
```
The issue was found by libFuzzer with a [Grammarinator](https://github.com/renatahodovan/grammarinator)-based custom mutator.

**Comment by bellard** [comment]
no longer relevant because libbf was removed.
