### ISSUE TITLE
Abort in get_ovop_from_opcode

### ISSUE THREAD

**Issue by renatahodovan** [bellard/quickjs#271]
Version: 3b45d15
Command: `ASAN_OPTIONS="handle_abort=1" ./qjs --bignum test.js`
Build: `CONFIG_ASAN=y make`
Test:
```js
var vec2_ops = Operators(
{
    right: Number,
    "*"(a, b) { }
});

var Vec2 = class Vec2 extends vec2_ops
{
    constructor(x, y) {
        super();
    }
}

var a = new Vec2(1, 2);
var b = new Vec2(3, 4);
a <= ~b;
```

Backtrace:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==4193927==ERROR: AddressSanitizer: ABRT on unknown address 0x03e9003ffe87 (pc 0x7f8df94029fc bp 0x0000003ffe87 sp 0x7fff89fc7cf0 T0)
    #0 0x7f8df94029fc in __pthread_kill_implementation nptl/pthread_kill.c:44
    #1 0x7f8df94029fc in __pthread_kill_internal nptl/pthread_kill.c:78
    #2 0x7f8df94029fc in __GI___pthread_kill nptl/pthread_kill.c:89
    #3 0x7f8df93ae475 in __GI_raise ../sysdeps/posix/raise.c:26
    #4 0x7f8df93947f2 in __GI_abort stdlib/abort.c:79
    #5 0x557cae80a40f in get_ovop_from_opcode quickjs/quickjs.c:12579
    #6 0x557cae86acc1 in js_call_unary_op_fallback quickjs/quickjs.c:12812
    #7 0x557cae8c92d0 in js_not_slow quickjs/quickjs.c:13125
    #8 0x557cae8502cf in JS_CallInternal quickjs/quickjs.c:18198
    #9 0x557cae8594f9 in JS_CallFree quickjs/quickjs.c:18695
    #10 0x557cae9ad235 in JS_EvalFunctionInternal quickjs/quickjs.c:34351
    #11 0x557cae9b0c1a in __JS_EvalInternal quickjs/quickjs.c:34486
    #12 0x557cae9a38bd in JS_EvalInternal quickjs/quickjs.c:34504
    #13 0x557cae9a38bd in JS_EvalThis quickjs/quickjs.c:34535
    #14 0x557cae9a38bd in JS_Eval quickjs/quickjs.c:34543
    #15 0x557cae80c761 in eval_buf quickjs/qjs.c:71
    #16 0x557cae80c957 in eval_file quickjs/qjs.c:103
    #17 0x557cae80b875 in main quickjs/qjs.c:516
    #18 0x7f8df9395d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #19 0x7f8df9395e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #20 0x557cae80be24 in _start (quickjs/qjs+0x35e24)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT nptl/pthread_kill.c:44 in __pthread_kill_implementation
==4193927==ABORTING
```
The issue was found by libFuzzer.

**Comment by bellard** [comment]
Operators() are no longer supported.
