### ISSUE TITLE
resolve_labels: Assertion `label_slots[i].first_reloc == NULL' failed

### ISSUE THREAD

**Issue by renatahodovan** [bellard/quickjs#282]
Version: 3b45d15
Command: ASAN_OPTIONS="handle_abort=1" `./qjs test.js`
Build: `CONFIG_ASAN=y make qjs`
Test:
```js
for (;;) {
  SIGALRM:break ;
  SIGALRM:break ;
  SIGALRM:break ;
}
```

Backtrace:
```
qjs: quickjs.c:32859: resolve_labels: Assertion `label_slots[i].first_reloc == NULL' failed.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1830816==ERROR: AddressSanitizer: ABRT on unknown address 0x03e9001befa0 (pc 0x7ffff76759fc bp 0x0000001befa0 sp 0x7fffffffd140 T0)
    #0 0x7ffff76759fc in __pthread_kill_implementation nptl/pthread_kill.c:44
    #1 0x7ffff76759fc in __pthread_kill_internal nptl/pthread_kill.c:78
    #2 0x7ffff76759fc in __GI___pthread_kill nptl/pthread_kill.c:89
    #3 0x7ffff7621475 in __GI_raise ../sysdeps/posix/raise.c:26
    #4 0x7ffff76077f2 in __GI_abort stdlib/abort.c:79
    #5 0x7ffff760771a in __assert_fail_base assert/assert.c:92
    #6 0x7ffff7618e95 in __GI___assert_fail assert/assert.c:101
    #7 0x55555566aee4 in resolve_labels quickjs/quickjs.c:32859
    #8 0x55555566aee4 in js_create_function quickjs/quickjs.c:33344
    #9 0x55555572ebce in __JS_EvalInternal quickjs/quickjs.c:34473
    #10 0x5555557218bd in JS_EvalInternal quickjs/quickjs.c:34504
    #11 0x5555557218bd in JS_EvalThis quickjs/quickjs.c:34535
    #12 0x5555557218bd in JS_Eval quickjs/quickjs.c:34543
    #13 0x55555558a761 in eval_buf quickjs/qjs.c:71
    #14 0x55555558a957 in eval_file quickjs/qjs.c:103
    #15 0x555555589875 in main quickjs/qjs.c:516
    #16 0x7ffff7608d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #17 0x7ffff7608e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #18 0x555555589e24 in _start (quickjs/qjs+0x35e24)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT nptl/pthread_kill.c:44 in __pthread_kill_implementation
==1830816==ABORTING
```
The issue was found by libFuzzer with a [Grammarinator](https://github.com/renatahodovan/grammarinator)-based custom mutator.

**Comment by bnoordhuis** [comment]
fyi, quickjs-ng/quickjs@66732e7 (which I landed to fix another bug) also fixes this bug

**Comment by bellard** [comment]
Unfortunately it does not fix the bug. Try:
for (;;) {
  SIGALRM:break  SIGALRM;
  SIGALRM:break  SIGALRM;
  SIGALRM:break  SIGALRM;
}
