### ISSUE TITLE
dynamic-stack-buffer-overflow in js_std_setenv

### ISSUE THREAD

**Issue by renatahodovan** [bellard/quickjs#284]
Version: 3b45d15
Command: `./qjs --std test.js`
Build: `CONFIG_ASAN=y make qjs`
Test:
```js
std.setenv();
```

Backtrace:
```gdb
=================================================================
==2000928==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7fffffffb870 at pc 0x5555558db2df bp 0x7fffffffb800 sp 0x7fffffffb7f8
READ of size 8 at 0x7fffffffb870 thread T0
    #0 0x5555558db2de in js_std_setenv quickjs/quickjs-libc.c:664:13
    #1 0x55555568956c in js_call_c_function quickjs/quickjs.c:16014:19
    #2 0x5555556de4a5 in JS_CallInternal quickjs/quickjs.c:16209:16
    #3 0x5555556f07d2 in JS_CallInternal quickjs/quickjs.c:16616:27
    #4 0x55555570def1 in JS_CallFree quickjs/quickjs.c:18695:19
    #5 0x55555570def1 in JS_EvalFunctionInternal quickjs/quickjs.c:34351:19
    #6 0x55555572ec70 in __JS_EvalInternal quickjs/quickjs.c:34486:19
    #7 0x55555570f2fb in JS_EvalInternal quickjs/quickjs.c:34504:12
    #8 0x55555570f2fb in JS_EvalThis quickjs/quickjs.c:34535:11
    #9 0x55555570f2fb in JS_Eval quickjs/quickjs.c:34543:12
    #10 0x55555568685d in eval_buf quickjs/qjs.c:71:15
    #11 0x555555686a9b in eval_file quickjs/qjs.c:103:11
    #12 0x5555556862eb in main quickjs/qjs.c:516:17
    #13 0x7ffff7c7ed8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #14 0x7ffff7c7ee3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #15 0x5555555ac6a4 in _start (quickjs/qjs+0x586a4) (BuildId: 3c4be6160e11eb38fd56eb90b29e90e412d3acf3)

Address 0x7fffffffb870 is located in stack of thread T0
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow quickjs/quickjs-libc.c:664:13 in js_std_setenv
Shadow bytes around the buggy address:
  0x7fffffffb580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffffffb600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffffffb680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffffffb700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffffffb780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7fffffffb800: 00 00 00 00 00 00 00 00 ca ca ca ca 00 00[cb]cb
  0x7fffffffb880: cb cb cb cb 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffffffb900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffffffb980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffffffba00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7fffffffba80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2000928==ABORTING
```
The issue was found by libFuzzer with a [Grammarinator](https://github.com/renatahodovan/grammarinator)-based custom mutator.

**Comment by bellard** [comment]
I cannot reproduce the issue.
