### ISSUE TITLE
Fewer <anonymous> functions in stack traces?

### ISSUE THREAD

**Issue by swankjesse** [bellard/quickjs#93]
Here’s a program that makes a stack trace:

```javascript
var dog = {};
dog.bark = function() {
  throw new Error('woof woof');
};
function makeStack() {
  try {
    dog.bark();
  } catch (error) {
    return error.stack;
  }
}
makeStack();
```

This is what QuickJS makes:

```
    at <anonymous> (file.js:3)
    at makeStack (file.js:7)
    at <eval> (file.js:12)
```

And Chrome:

```
Error: woof woof
    at Object.dog.bark (file.js:3:9)
    at makeStack (file.js:7:9)
    at file.js:12:1
```

And Firefox:

```
dog.bark@file.js eval code:3:9
makeStack@file.js eval code:7:9
@file.js eval code:12:1
```

Both Chrome and Firefox include _dog.bark_ in the stack trace, but in QuickJS this function is `<anonymous>`.

Getting the function name in the output is super handy. This example is trivial, but my real program has deep stacks full of `<anonymous>` and it slows down debugging.

**Comment by swankjesse** [comment]
(QuickJS still puts Safari to shame though!)

```
@
makeStack@
global code@
evaluateWithScopeExtension@[native code]
@
_wrapCall@
```

**Comment by wanhongbo** [comment]
Is there any progress on this issue？

**Comment by chqrlie** [comment]
Not yet, currently focusing on other issues: ropes, bug fixes and support for recent tc39 extensions.

Chqrlie.

**Comment by wanhongbo** [comment]
`
function makeStack() {
  try {
    this.xxxx()
  } catch (error) {
    console.log(error.stack)
    console.log(error.message)
  }
}
makeStack();`

The above code does not display xxxx in call stack when it fails :(
